#!/bin/bash
set -o xtrace
if [ -z "$1" ];then
	echo "Please specify interface to lock down"
	exit 1
fi

iptables -I INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT


for x in `ip route | grep ^default | grep $1 | awk '{print($3)}'`;do
	iptables -I INPUT 1 -i $1 -s $x -p tcp --dport 22 -j ACCEPT
done
for x in `ip addr show $1 | grep inet\  | awk '{print($2)}'`;do
	iptables -I INPUT 1 -i $1 -s $x -p tcp -j DROP
done

for x in `ip route | grep ^default | grep $1 | awk '{print($3)}'`;do
	ip6tables -I INPUT 1 -i $1 -s $x -p tcp --dport 22 -j ACCEPT
done
for x in `ip addr show $1 | grep inet6\  | awk '{print($2)}'`;do
	ip6tables -I INPUT 1 -i $1 -s $x -p tcp -j DROP
done

iptables -L -v -n
ip6tables -L -v -n
